### ISSUE TITLE
V5 connection connack missing authentication method

### ISSUE THREAD

**Issue by michaelg9** [hivemq/hivemq-community-edition#110]
## Expected behavior
The CONNACK packet sent by the broker in response to a successful v5 client authentication request must contain the same authentication method value as specified by the CONNECT packet, as specified in the MQTTv5 protocol specification:
If the initial CONNECT packet included an Authentication Method property then all AUTH packets, and any successful CONNACK packet MUST include an Authentication Method Property with the same value as in the CONNECT packet [MQTT-4.12.0-5].
## Actual behavior
At the moment the v5 CONNACK is always sent with an empty authentication method field
### Steps
Use a v5 client (hivemq client works as well) to authenticate with the broker using an extended authentication method (in my case it's an extension of SimpleAuthenticator). The broker successfully authenticates the client and sends a CONNACK but the client rejects the connection because of this

## Details
- Affected HiveMQ CE version(s): latest
- Used JVM version: 11
## Proposed bugfix:
In ConnectHandler.java, method buildMqtt5Connack:
```java
        final CONNACK.Mqtt5Builder builder = new CONNACK.Mqtt5Builder()
                .withSessionPresent(sessionPresent)
                .withReasonCode(Mqtt5ConnAckReasonCode.SUCCESS)
                .withReceiveMaximum(configurationService.mqttConfiguration().serverReceiveMaximum())
                .withSubscriptionIdentifierAvailable(configurationService.mqttConfiguration().subscriptionIdentifierEnabled())
                .withMaximumPacketSize(configurationService.mqttConfiguration().maxPacketSize())
                .withWildcardSubscriptionAvailable(configurationService.mqttConfiguration().wildcardSubscriptionsEnabled())
                .withSharedSubscriptionAvailable(configurationService.mqttConfiguration().sharedSubscriptionsEnabled())
                .withMaximumQoS(configurationService.mqttConfiguration().maximumQos())
                .withRetainAvailable(configurationService.mqttConfiguration().retainedMessagesEnabled());
```
A ```.withAuthMethod(msg.getAuthMethod());``` is missing from there

**Comment by SgtSilvio** [comment]
Hi @michaelg9 
This issue will be solved when enhanced authentication is exposed to the extension SDK.
Enhanced authentication will be implemented soon. We will then link and close this ticket.

**Comment by michaelg9** [comment]
Hi
When will this feature be published to the SDK repo?
