### ISSUE TITLE
Windows service doesn't work

### ISSUE THREAD

**Issue by MicWalter** [hivemq/hivemq-community-edition#112]
Follow up ticket from discussion:
https://community.hivemq.com/t/hivemq-as-windows-service/108

## Expected behavior
Following the steps for installing HiveMQ as a windows service, I would expect a running HiveMQ service.

## Actual behavior
The used wrapper is not working with the Java versions required by HiveMQ CE (at least Java 11).

### Steps
* Download [HiveMQ CE](https://github.com/hivemq/hivemq-community-edition/releases)
* Download the [windows service zip](https://www.hivemq.com/docs/4.2/hivemq/install-hivemq.html#windows)
* Start normal -> works
* Install HiveMQ as a service (follow steps [here](https://www.hivemq.com/docs/4.2/hivemq/install-hivemq.html#windows))
* Service is installed but can't be started:
![Bildschirmfoto 2019-11-20 um 10 28 35](https://user-images.githubusercontent.com/30898894/69226617-b6464780-0b80-11ea-81c6-bdb049358092.png)

## Details
- Affected HiveMQ CE version(s): Any
- Used JVM version: 11.0.2 and 12.0.2
- Tested Windows version: Windows 10 Pro (version 1803) and Windows 10 Enterprise (version 18362)

**Comment by MicWalter** [comment]
I also tested the newest YAJSW version (12.14): I just copied the wrapper.conf from the old conf folder to the new conf folder -> still didn't work

My assumption is that the wrapper.conf must be updated with the new java options.

Proposal: Instead of wrapping the hivemq.jar the run.bat should be wrapped, that would eliminate  the need to update the windows service zip each time java options change to run HiveMQ 4.

**Comment by DC2-DanielKrueger** [comment]
@MicWalter do you know if this is still true?

**Comment by akshayagashe06** [comment]
Hello @MicWalter, @DC2-DanielKrueger 
Can you let me know the fix to this issue? 
I am facing the same problem while starting the service with OpenJDK 19. 

Thank you.
