### ISSUE TITLE
Wrong Connack Reason code for Bad username or password

### ISSUE THREAD

**Issue by michaelg9** [hivemq/hivemq-community-edition#119]
## Expected behavior
When an authenticator sets that the client failed authentication with reason code BAD USERNAME OR PASSWORD, the client should receive this same code
## Actual behavior
The client receives BAD_AUTHENTICATION_METHOD reason code instead
### Steps
Just create an extension and fail the requested connect packet with a BAD_USERNAME_OR_PASSWORD reason code and see that the client receives BAD_AUTHENTICATION_METHOD.
### Buggy code
In ReasonCodeUtil.java, this extract of code:

```java
            case BAD_USER_NAME_OR_PASSWORD:
                return Mqtt5ConnAckReasonCode.BAD_AUTHENTICATION_METHOD;
            case SERVER_UNAVAILABLE:
                return Mqtt5ConnAckReasonCode.SERVER_UNAVAILABLE;
            case SERVER_BUSY:
                return Mqtt5ConnAckReasonCode.SERVER_BUSY;
            case BANNED:
                return Mqtt5ConnAckReasonCode.BANNED;
            case BAD_AUTHENTICATION_METHOD:
                return Mqtt5ConnAckReasonCode.BAD_AUTHENTICATION_METHOD;
```
Obviously, the first one is wrong and should be:
```java
            case BAD_USER_NAME_OR_PASSWORD:
                return Mqtt5ConnAckReasonCode.BAD_USER_NAME_OR_PASSWORD;
```

## Details
- Affected HiveMQ CE version(s): latest
- Used JVM version: 11

**Comment by SgtSilvio** [comment]
@michaelg9 
Good catch 👍 
If you want, you can open a PR for this.

**Comment by michaelg9** [comment]
Pull request [here](https://github.com/hivemq/hivemq-community-edition/pull/120)

**Comment by SgtSilvio** [comment]
@michaelg9 Thanks again for your contribution, your PR is now merged
