### ISSUE TITLE
About the HIveMQ authentication MQTT client user password method

### ISSUE THREAD

**Issue by wenyanwen** [hivemq/hivemq-community-edition#127]
hello,
Dear author
I wonder how HiveMQ CE enables MQTT client user password authentication

I did not find any information in the literature about HIveMQ's method of validating MQTT client user passwords but  It supports
Can you tell me how to configure it?

**Comment by schaebo** [comment]
Hi wenyanwen,

HiveMQ handles authentication and authorization via extensions.

You can implement your custom logic or use any of the already available extensions like the File RBAC extension (https://github.com/hivemq/hivemq-file-rbac-extension).

**Comment by wenyanwen** [comment]
Hi, HiveMQ community office supports File RBAC extension, right

**Comment by schaebo** [comment]
yes, the file rbac extension works with the community edition.
