### ISSUE TITLE
Does too much topic affect performance

### ISSUE THREAD

**Issue by wenyanwen** [hivemq/hivemq-community-edition#130]
Please inform me.   Does too much topic affect performance

**Comment by SgtSilvio** [comment]
Hi @wenyanwen 
The best place for your question would be the HiveMQ community forum: https://community.hivemq.com/
As a quick answer, in MQTT topics are just metadata to route the messages to the right subscribers. So the amount of topics is not a factor that impacts performance.

**Comment by fraschbi** [comment]
Please refer all discussion to the HiveMQ Community Forum.
I think [this thread may](https://community.hivemq.com/t/how-many-topic-can-the-hivemq-ce-create/107) interest you.
Thank you.
