### ISSUE TITLE
too much consumption at single-writer task

### ISSUE THREAD

**Issue by hellocarter** [hivemq/hivemq-community-edition#132]
I've made some prossure testing on HiveMQ-CE, I found that single-writer-x thread cost so much CPU and MEM. 
The server is 8C 32G ubuntu, I made 10k connections, then subscribe 5k topics, then publish to these topics at the rate of 22k QPS with Qos1. It performs well with 10min, but faded after 10min, I found the cpu idle time is almost to 0%, but another broker moquette works well.
Is it that xodus cannot support the QPS?

jatack
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
22896 root      20   0 15.930g 8.464g  26656 R 35.6 26.9   3:31.59 single-writer-8
22891 root      20   0 15.930g 8.464g  26656 R 35.2 26.9   3:29.03 single-writer-3
22901 root      20   0 15.930g 8.464g  26656 R 34.9 26.9   3:29.40 single-writer-1
22894 root      20   0 15.930g 8.464g  26656 R 33.6 26.9   3:30.63 single-writer-6
22900 root      20   0 15.930g 8.464g  26656 R 33.2 26.9   3:30.84 single-writer-1
22888 root      20   0 15.930g 8.464g  26656 R 32.9 26.9   3:30.61 single-writer-0
22892 root      20   0 15.930g 8.464g  26656 R 32.9 26.9   3:30.92 single-writer-4
22893 root      20   0 15.930g 8.464g  26656 R 32.6 26.9   3:30.24 single-writer-5
22899 root      20   0 15.930g 8.464g  26656 R 32.6 26.9   3:30.16 single-writer-1
22890 root      20   0 15.930g 8.464g  26656 R 31.6 26.9   3:29.70 single-writer-2
22902 root      20   0 15.930g 8.464g  26656 R 31.2 26.9   3:30.56 single-writer-1
22889 root      20   0 15.930g 8.464g  26656 R 30.9 26.9   3:30.93 single-writer-1
22898 root      20   0 15.930g 8.464g  26656 R 30.9 26.9   3:30.24 single-writer-1
22903 root      20   0 15.930g 8.464g  26656 R 30.9 26.9   3:28.89 single-writer-1
22897 root      20   0 15.930g 8.464g  26656 R 30.2 26.9   3:30.25 single-writer-9
22895 root      20   0 15.930g 8.464g  26656 R 29.9 26.9   3:30.15 single-writer-7

**Comment by fraschbi** [comment]
Hi @hellocarter,

Thank you for reaching out.
In short: HiveMQ CE absolutely supports 22k QPS.
If you need guidance on properly configuring and using HiveMQ, feel free top open a thread in our [Community Forum](https://community.hivemq.com/c/hivemq-community-edition/6). It is the right place for such discussions.

Regards,
Florian

**Comment by hellocarter** [comment]
Hi @fraschbi ,
Thank you for your reply, I've singned on the forum in order to post this question and to upload some test result pictures, but I was not permitted to post a topic.
