### ISSUE TITLE
Does the community version support JDK 8?

### ISSUE THREAD

**Issue by Johnnie843** [hivemq/hivemq-community-edition#157]

**Comment by fraschbi** [comment]
Hi @Johnnie843 ,
For future references please direct your questions to the HiveMQ Community Forum (community.hivemq.com). GitHub Issues are meant for reports of unwanted behaviour only.
The [System Requirements](https://github.com/hivemq/hivemq-community-edition/wiki/System-Requirements) state the following:

> Production: OpenJDK JRE 11 or newer is required.
> Development: OpenJDK JDK 11 or newer is recommended.

Kind regards,
Florian
