### ISSUE TITLE
 A recommendation

### ISSUE THREAD

**Issue by wenyanwen** [hivemq/hivemq-community-edition#162]
Hello, developer, I want to make a suggestion. Can you add a web control center to the community version to better use the community version?

**Comment by fraschbi** [comment]
Hi @wenyanwen,

Thank you for your recommendation. The HiveMQ Control Center is part of the Professional and Enterprise Editions. Currently there are no plans to add to the Community Editions.
You can see the differences in editions here: https://www.hivemq.com/hivemq/editions/

Kind regards,
Florian
