### ISSUE TITLE
MacOS: 10.13.6 Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by xchen10bu** [hivemq/hivemq-community-edition#165]
Every time I run the ./run.s command in console, I get the issue where it stops and gives me this log:

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/home/nodegui-starter/dist/nodegui_core-a4391044d9abfaee06413a761a612272.node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/home/nodegui-starter/dist/nodegui_core-a4391044d9abfaee06413a761a612272.node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
Is there a mac version requirement for this? Or is there a work around it ? Thanks.

**Comment by HiveMQSupport** [comment]
Hi @xchen10bu,

Seems like an [issue](https://github.com/nodegui/nodegui/issues/391) with NodeGUI.
Do you have NodeGUI installed?

**Comment by fraschbi** [comment]
It looks like this an [issue](https://github.com/nodegui/nodegui/issues/391) with NodeGUI.

**Comment by DanielJosefKrueger** [comment]
Here is more information on this issue: https://github.com/nodegui/nodegui/issues/391. I have the same problem and will switch to a newer Mac OS version.

**Comment by DC2-DanielKrueger** [comment]
What Mac version are you using?

**Comment by DC2-DanielKrueger** [comment]
Closed, issue is already reported here https://github.com/nodegui/nodegui/issues/391.
