### ISSUE TITLE
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gnupg2/gnupg-l10n_2.2.12-1+deb10u1_all.deb  Hash Sum mismatch

### ISSUE THREAD

**Issue by dollars365** [hivemq/hivemq-community-edition#177]
use command： ./docker/build.sh
get issue:
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gnupg2/gnupg-l10n_2.2.12-1+deb10u1_all.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:e7157cc999402118a01919b90be27249e70ae830d06a5dc42e9069ed230926be
    - MD5Sum:167d83c96ff2cc68d92ab64b5bb45c45 [weak]
    - Filesize:1009612 [weak]
   Hashes of received file:
    - SHA256:4aa95992b6943bca5d298ace028642822dd23407e339e89e66a41255132fcd05
    - MD5Sum:cd95020433c279ed3a874d5bc26d0ec8 [weak]
    - Filesize:1009612 [weak]
   Last modification reported: Sun, 01 Sep 2019 03:14:20 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by fraschbi** [comment]
Hi @dollars365,

The build is running fine for me.
Did you try running `apt-get update`?

Regards,
Florian

**Comment by DC2-DanielKrueger** [comment]
I close this issue for now, because there was no reaction for over half a year. Please feel free to re-open, if it is still a problem. 

Best regards, 

Daniel

**Comment by DarkSnowJR** [comment]
Failed to fetch http://deb.debian.org/debian/pool/main/libd/libdap/libdapclient6v5_3.20.7-6_amd64.deb  Connection timed out
