### ISSUE TITLE
mqtt terminating issue

### ISSUE THREAD

**Issue by vigneshbeei** [hivemq/hivemq-community-edition#18]
i am using HiveMQ MQTT broker in AWS EC2 ubuntu 18. mqtt works fine in AWS t2.micro, but moves to t2.medium it start terminating. If i again move to t2.micro works good. i don't know why mqtt start terminating if i move to t2.medium. i did't use SSL/TLS.

Mosquitto.conf
pid_file /var/run/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/
log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
require_certificate false
log_type all

please help me for this issue.
Thanks in asvance.

**Comment by fraschbi** [comment]
Hi @vigneshbeei,

In accordance with our [Contribution Guidelines](https://github.com/hivemq/hivemq-community-edition/blob/master/CONTRIBUTING.adoc#issues) I would kindly ask you not to use our GitHub issues for questions.

Kind regards,
Florian
