### ISSUE TITLE
RocksDB "LOG" statistics file using unnecessary amount of storage.

### ISSUE THREAD

**Issue by josephverburg** [hivemq/hivemq-community-edition#183]
Every RocksDB bucket used by HiveMQ by default generates a statistics report every 10 minutes, with the amount of 320 buckets in HiveMQ (5 * 64) this effectively means that every 2 seconds a report is generated.

For our use this means a steady storage consumption of 300 MB / day or 10 GB / month.

This stems from the following RocksDB behaviour: https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide (search for "stats_dump_period_sec")

## Expected behavior
Limit on the RocksDB bucket "LOG" file filesize or greatly reduced "stats_dump_period_sec" by default in HiveMQ for the RocksDB buckets.

## Actual behavior
The RocksDB bucket "LOG" file keeps growing infinitely, we so far saw usage of over 30GB just by these LOG files. 

### Steps
- Setup HiveMQ server with default configuration
- Have some basic usage (few messages per minute to make sure the RocksDB is used, the "LOG" file is not written to when the database is not used)

### Reproducer code
N/A

## Details
- Affected HiveMQ CE version(s): 2020.2
- Used JVM version: 11

**Comment by canique** [comment]
This is bad for SSD disks. Having the same problem. A fix would be good.

**Comment by MicWalter** [comment]
**Changes:**
* LOG files can only grow to 500kB
* only two LOG files can exists at one time (older LOG will be deleted) per bucket
* statistical information are no longer written into LOG
* buffer size per bucket has been reduced to 64KB (before 1MB)

Therefore the hard disk space taken up by LOG files in the Commnity Edition should be at most 125MB now.

Calculation: 2 persistence use RocksDB (each having 64 buckets), per bucket only two LOG files with max size of 500KB can be created -> 2 * 64 * 2 * 500KB = ~125MB

Will be part of the 2020.6 release
