### ISSUE TITLE
Proxy Protocol does not work with HAProxy 2.1.7

### ISSUE THREAD

**Issue by canique** [hivemq/hivemq-community-edition#184]
## Expected behavior
Logs should show real IP address of client

## Actual behavior
error message: "Client ID: UNKNOWN, IP: 192.168.0.1 was disconnected. reason: Sent other message before CONNECT."

### Steps
configure haproxy with a TCP backend like this:
```
defaults MQTT
  mode tcp
frontend ft_mqtt
  bind E.X.TERNAL.IP:8883 transparent ssl crt /etc/ssl/letsencrypt/certs/my.haproxy.pem
  default_backend bk_mqtt
backend bk_mqtt
  server hivemq1 192.168.0.1:1883 send-proxy-v2-ssl-cn check inter 30s downinter 30s fastinter 250ms fall 3 rise 2

```
configure hivemq with
```
<listeners>
        <tcp-listener>
            <port>1883</port>
            <bind-address>192.168.0.1</bind-address>
            <proxy-protocol>true</proxy-protocol>
        </tcp-listener>
    </listeners>
```

## Details
- Affected HiveMQ CE version(s): hivemq-ce-2020.2
- Used JVM version: Java 11.0.7

**Comment by MicWalter** [comment]
Hello @canique,

sorry for the delayed reply. 

The HiveMQ community edition doesn't support the proxy protocol at the moment (see [edition differences](https://www.hivemq.com/hivemq/editions/)).

Greetings,
Michael

**Comment by MicWalter** [comment]
Closing this issue, as proxy protocol is currently not supported in the community edition
