### ISSUE TITLE
Filter MQTT protocol on HiveMQ

### ISSUE THREAD

**Issue by ivanv6** [hivemq/hivemq-community-edition#185]
## Problem or use case
Hello, there is a parameter in the configuration file to set the MQTT version of the broker? For example, if i want only MQTT v3.1.1 connections, how i discard the other versions (v5, etc)?

Thanks!

## Preferred solution or suggestions
A parameter in the configuration file

**Comment by fraschbi** [comment]
Hi @ivanv6 ,

Thank you for reaching out.
It is not possible to limit the supported MQTT protocol versions.
If you are looking for a solution like this you could utilise the HiveMQ Extension SDK and check the protocol version of connecting clients.
Please refer to our [Community Forum](https://community.hivemq.com) for further discussions.
Best regards,
Florian
