### ISSUE TITLE
To add a command line parameter for "run.bat" / "run.sh" to manually select the JRE/JDK "java(.exe)" path

### ISSUE THREAD

**Issue by jayjupdhig** [hivemq/hivemq-community-edition#194]
## Problem or use case
My JRE/JDK in %path% variable is smaller then Version 11

## Preferred solution or suggestions
To add a command line parameter for "run.bat" / "run.sh" to manually select the JRE/JDK "java(.exe)" path

-> https://community.hivemq.com/t/how-to-define-jre-11-if-jre-11-is-not-in-command-path/282/2

With kind regards,
Jan

**Comment by martijintro** [comment]
???

**Comment by martijintro** [comment]
No anwser?!?

**Comment by jayjupdhig** [comment]
problem is still pendent!!

**Comment by jayjupdhig** [comment]
Problem solved by using Mosquitto... ;-)

Thank you for your understanding.


With kind regards from Switzerland,
Jan
