### ISSUE TITLE
Message "HiveMQ requires at least Java 11" but Java 12 is installed

### ISSUE THREAD

**Issue by chrispi68** [hivemq/hivemq-community-edition#20]
Java 12 is installed unter Windows but I get the message "ERROR! HiveMQ requires at least Java 11" and the broker will not start.

**Comment by sauroter** [comment]
Hi @chrispi68,

nice to see your interest in HiveMQ Community Edition and thank you for bringing the issue to our attention.

Could you please provide more information about your setup, like Windows version, java version and the complete HiveMQ start log.

Some helpful commands might be:
`winver`
`java -version`

Right now I can't reproduce the described behavior with Windows 10 (1809) and java version "12" 2019-03-19. 

Kind regards

Georg

**Comment by MinChanSike** [comment]
I also got that issue.
OS: Windows 10 Version 1803 (OS Build 17134.829)

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by sauroter** [comment]
Hi @MinChanSike,
looks like you are using the wrong java version:
> java version "1.8.0_211"
That means in Java speak version 8. But HiveMQ needs at least version 11 to run.

Here is a nice StackExchange post on how to do that under Windows: https://superuser.com/questions/1057532/how-to-change-java-version-on-windows-10

Have a good day
Georg
