### ISSUE TITLE
Incorrect byte value check during UTF-8 validation.

### ISSUE THREAD

**Issue by silh** [hivemq/hivemq-community-edition#205]
## Expected behavior
A proper check is performed.

## Actual behavior
Condition always resolves to true

### Steps
-

### Reproducer code
-

## Details
- Affected HiveMQ CE version(s): master
- Used JVM version: 11

In method com.hivemq.util.Utf8Utils#hasControlOrNonCharacter(byte[]) a following check is performed:
```
if (byte1 == (byte) 0xC2 && bytes[i + 1] >= (byte) 0x80 && bytes[i + 1] <= (byte) 0x9F)
```

where a second condition always resolves to true because `(byte) 0x80` equals to -128 and value of `bytes[i + 1]` could not be lover than that.

**Comment by DC2-DanielKrueger** [comment]
Thank you very much for your input.

this is now resolved with https://github.com/hivemq/hivemq-community-edition/pull/254
