### ISSUE TITLE
Define ClientLifecycleEventListener's methods with default

### ISSUE THREAD

**Issue by semenmiroshnichenko** [hivemq/hivemq-community-edition#21]
## Problem or use case
When implementing ClientLifecycleEventListener interface, one basically may not need for onAuthenticationSuccessful() but still have to override it and let empty method body.

## Preferred solution or suggestions
Mark onMqttConnectionStart(), onAuthenticationSuccessful() and onDisconnect() with default keyword so extension developer may override only methods he/she needs.

**Comment by fraschbi** [comment]
Hi @semenmiroshnichenko,
Thank you for your input. Nice to see you are interested and engaged in the HiveMQ Extension SDK.
After some internal discussion we decided, to not implement defaults for the method you mentioned.

Kind regards,
Florian
