### ISSUE TITLE
Question: support for ARM / ARM64 

### ISSUE THREAD

**Issue by JoergWende** [hivemq/hivemq-community-edition#216]
## Problem or use case
Want to run MQTT on ARM devices

## Preferred solution or suggestions
Provide some hints to run it on Raspberry PI - either native install or Docker 
at least an indication if it does not make sense to try it ....
J.

**Comment by Hart87** [comment]
I've run it with the shell commands on Raspian and had no issues. Didn't try it with a container.

**Comment by DC2-DanielKrueger** [comment]
basically just build the zip yourself or use the release. Important: use "file" or "in-memory" for persistence mode, because i think you wont have the RocksDB libraries.

Best regards, 

Daniel

**Comment by SgtSilvio** [comment]
Closing this as this should work.
