### ISSUE TITLE
OSHI dependency is quite old

### ISSUE THREAD

**Issue by andrewmcguinness** [hivemq/hivemq-community-edition#224]
## Problem or use case

Dependency on OSHI is version 3.6.2

This in turn pulls in 4.5.1 of JNA, which causes conflicts with libraries using newer versions of JNA, such as Azure SDK.

## Preferred solution or suggestions

Current version of JNA is 5.6.0 -- even bumping to the last v3 OSHI pulls in that (OSHI 3.13.6). Current version of OSHI is 5.3.x

https://github.com/hivemq/hivemq-community-edition/blob/master/gradle.properties#L20

**Comment by MicWalter** [comment]
Related PR: #228

**Comment by MicWalter** [comment]
Issue closed as OSHI was updated to 5.3.6
