### ISSUE TITLE
I want to get the event information when the client subscribes to topic

### ISSUE THREAD

**Issue by wolfdriver** [hivemq/hivemq-community-edition#23]
## Problem or use case

I want to get the event information when the client subscribing to the topic, and get the topic information that the client subscribing to for some processing.

But I don't know which HiveMQ Extension is more appropriate to use.

**Comment by fraschbi** [comment]
Hi @wolfdriver,
For questions surrounding the HIveMQ Community Edition please refer to the [HiveMQ Community Forum](http://community.hivemq.com).
The issue trigger is meant for reporting actual issues within the HiveMQ Community Edition Source Code only.

Thank you and kind regards,
Florian from the HIveMQ Team.
