### ISSUE TITLE
Support multiple EmbeddedExtension

### ISSUE THREAD

**Issue by gcdd1993** [hivemq/hivemq-community-edition#230]
## Problem or use case
now `EmbeddedHiveMQBuilder` only allow use one embedded extension
```java
  /**
   * Sets the {@link EmbeddedExtension} to the given argument.
   *
   * @param embeddedExtension the used embedded extension.
   * @return this builder.
   */
  @NotNull EmbeddedHiveMQBuilder withEmbeddedExtension(@Nullable EmbeddedExtension embeddedExtension);
```

## Preferred solution or suggestions
Are there any plans to support multiple embedded extensions?

**Comment by SgtSilvio** [comment]
Hi @gcdd1993 
There are no plans to support multiple embedded extensions.
Can you please describe which use case you need this for?

**Comment by gcdd1993** [comment]
If I develop more than one embedded extension, i just want to add all them to my embedded hivemq instance, instead of using them externally.

Can u provide a func like:
```java
@NotNull EmbeddedHiveMQBuilder addEmbeddedExtension(@Nullable EmbeddedExtension embeddedExtension);
```

**Comment by zpaimon** [comment]
Are there any plans to support multiple embedded extensions?

**Comment by DC2-DanielKrueger** [comment]
As there are no plans for supporting multiple embedded extensions, I will close this ticket.
