### ISSUE TITLE
EmbeddedHiveMQ automatically stoped after started successfully

### ISSUE THREAD

**Issue by rawli** [hivemq/hivemq-community-edition#257]
## Expected behavior
EmbeddedHiveMQ should not automatically stop after it had started. 
## Actual behavior
2021-03-18 10:48:55,564 INFO  - Starting HiveMQ extension system.
2021-03-18 10:48:55,615 INFO  - Starting TCP listener on address 0.0.0.0 and port 1883
2021-03-18 10:48:55,693 INFO  - Started TCP Listener on address 0.0.0.0 and on port 1883
2021-03-18 10:48:55,693 INFO  - Started EmbeddedHiveMQ in 7601ms
2021-03-18 10:48:55,694 INFO  - Closing EmbeddedHiveMQ.
2021-03-18 10:48:57,905 INFO  - Shutting down extension system
2021-03-18 10:49:03,448 INFO  - Stopped EmbeddedHiveMQ in 7754ms
## To Reproduce
SpringBoot integrate hivemq-community-edition-embedded 2021.1
### Steps
Start the SpringBoot application.
### Reproducer code
@SpringBootApplication
public class HlgmdApplication implements CommandLineRunner {
	
	public static void main(String[] args) {
		SpringApplication.run(HlgmdApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		if (args.length > 0) {

		}
		File hivemqConfig = new File("hivemq-config");
		if((!hivemqConfig.exists()) || (!hivemqConfig.isDirectory())) {
			hivemqConfig.mkdirs();
		}
		File hivemqData = new File("hivemq-data");
		if((!hivemqData.exists()) || (!hivemqData.isDirectory())) {
			hivemqData.mkdirs();
		}
		File hivemqExtensions = new File("hivemq-extensions");
		if((!hivemqExtensions.exists()) || (!hivemqExtensions.isDirectory())) {
			hivemqExtensions.mkdirs();
		}
		final EmbeddedHiveMQBuilder embeddedHiveMQBuilder = EmbeddedHiveMQ.builder()
				.withConfigurationFolder(Path.of("hivemq-config"))
				.withDataFolder(Path.of("hivemq-data"))
				.withExtensionsFolder(Path.of("hivemq-extensions"));
		try (final EmbeddedHiveMQ hiveMQ = embeddedHiveMQBuilder.build()) {
			hiveMQ.start().join();
		} catch (final Exception ex) {
			ex.printStackTrace();
		}
	}

}
## Details
- Affected HiveMQ CE version(s): hivemq-community-edition-embedded 2021.1
- Used JVM version:11

**Comment by DC2-DanielKrueger** [comment]
Hallo wali, 
 
Your using the ARM feature of Java (automatic ressource management):
`try (something autoclosable){}`

After the try-block finishes all resources - this is the Embedded HiveMQ - gets closed. Just build it inside the try block and not in the () brackets:

```
try {
  final EmbeddedHiveMQ hiveMQ = embeddedHiveMQBuilder.build();
  hiveMQ.start().join();
} catch (final Exception ex) {
  ex.printStackTrace();
}

```
