### ISSUE TITLE
ClientTlsInformation class not found

### ISSUE THREAD

**Issue by alexrobin** [hivemq/hivemq-community-edition#265]
When a `ClientInitializer` is registered in an extension, no client can connect.

Internally, there is a ClassNotFound exception raised because `ClientTlsInformationImpl` implements `ClientTlsInformation` but `com.hivemq.extension.sdk.api.client.parameter.ClientTlsInformation` is nowhere to be found in the extension SDK jar.

- Affected HiveMQ CE version(s): 2021.1 which depends on `hivemq-extension-sdk-4.5.1.jar`
- Used JVM version: JDK 11

**Comment by DC2-DanielKrueger** [comment]
Hallo @alexrobin,

Do you use the EmbeddedVersion of HiveMQ CE?

Best regards, 

Daniel

**Comment by alexrobin** [comment]
Yes, I do.

**Comment by DC2-DanielKrueger** [comment]
Ok, the problem are the changes that are already included in the master of the extension sdk, but not published yet. We need to fix that. In the meantime the best way would be to use version2020.6. Is this possible for you?

**Comment by alexrobin** [comment]
Ok, good to know. Actually I was able to make it work temporarily by just adding an empty `com.hivemq.extension.sdk.api.client.parameter.ClientTlsInformation` interface in my own code. I know it's a hack but it works for me until you release the next version.

**Comment by DC2-DanielKrueger** [comment]
Ah nice idea, however i would not use that hack in prod (guess you are not doing so).

 i leave this issue open for others to find it. I update you when we release the extension sdk version that contains the necessary classes.

**Comment by DC2-DanielKrueger** [comment]
BTW: you can find the "real" class here: https://github.com/hivemq/hivemq-extension-sdk/blob/master/src/main/java/com/hivemq/extension/sdk/api/client/parameter/ClientTlsInformation.java

**Comment by alexrobin** [comment]
Sure, not for production, just for testing. I'll update to the new extension SDK as soon as you release it. Thanks.

**Comment by DC2-DanielKrueger** [comment]
It should be released by now. Ill close this.

**Comment by alexrobin** [comment]
So I should update dependency hivemq-extension-sdk to 4.6.1, correct? (HiveMQ CE 2021.1 uses 4.5.1)

**Comment by DC2-DanielKrueger** [comment]
yeah exactly, use the latest minor version, that is 4.6.X and its latest maintenance release is 4.6.1
