### ISSUE TITLE
Building from Source get compileJava FAILED

### ISSUE THREAD

**Issue by yilezhu** [hivemq/hivemq-community-edition#275]
When I download the source code and compile it, the compilation always fails.The error is as follows

`[root@localhost hivemq-community-edition]# ./gradlew hivemqZip
######################################################################################################
You can not use the latest changes of or modify the hivemq-extension-sdk.
Please checkout the hivemq-extension-sdk repository next to the hivemq-community-edition repository.
Execute the following command from your project directory:
git clone https://github.com/hivemq/hivemq-extension-sdk.git ../hivemq-extension-sdk
You can also clone your fork:
git clone https://github.com/<replace-with-your-fork>/hivemq-extension-sdk.git ../hivemq-extension-sdk
######################################################################################################

> Task :compileJava
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/ExtensionInformationUtil.java:113: 错误: 找不到符号
    public static @Nullable ClientTlsInformation getTlsInformationFromChannel(final @NotNull Channel channel) {
                            ^
  符号:   类 ClientTlsInformation
  位置: 类 ExtensionInformationUtil
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/client/parameter/ClientTlsInformationImpl.java:21: 错误: 找不到符号
import com.hivemq.extension.sdk.api.client.parameter.ClientTlsInformation;
                                                    ^
  符号:   类 ClientTlsInformation
  位置: 程序包 com.hivemq.extension.sdk.api.client.parameter
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/client/parameter/ClientTlsInformationImpl.java:31: 错误: 找不到符号
public class ClientTlsInformationImpl implements ClientTlsInformation, TlsInformation {
                                                 ^
  符号: 类 ClientTlsInformation
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/client/parameter/ConnectionInformationImpl.java:40: 错误: 找不到符号
    private final @Nullable ClientTlsInformation tlsInformation;
                            ^
  符号:   类 ClientTlsInformation
  位置: 类 ConnectionInformationImpl
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/client/parameter/ConnectionInformationImpl.java:89: 错误: 找不到符号
    public @NotNull Optional<ClientTlsInformation> getClientTlsInformation() {
                             ^
  符号:   类 ClientTlsInformation
  位置: 类 ConnectionInformationImpl
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/client/parameter/ClientTlsInformationImpl.java:68: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/client/parameter/ClientTlsInformationImpl.java:73: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/client/parameter/ClientTlsInformationImpl.java:88: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/client/parameter/ConnectionInformationImpl.java:88: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/root/hivemq-community-edition/src/main/java/com/hivemq/extensions/packets/connack/ModifiableConnackPacketImpl.java:145: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
10 个错误

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed
[root@localhost hivemq-community-edition]# java -version
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
[root@localhost hivemq-community-edition]#
`

**Comment by DC2-DanielKrueger** [comment]
Hallo, 
The first lines o the error explains the problem:

```
You can not use the latest changes of or modify the hivemq-extension-sdk.
Please checkout the hivemq-extension-sdk repository next to the hivemq-community-edition repository.
Execute the following command from your project directory:
git clone https://github.com/hivemq/hivemq-extension-sdk.git ../hivemq-extension-sdk
You can also clone your fork:
git clone https://github.com//hivemq-extension-sdk.git ../hivemq-extension-sdk
```

Simply clone the extension sdk in the same folder as u did with the CE and u should be fine. 

Best regards, 
Daniel

**Comment by yilezhu** [comment]
Great. I'm careless. Thank you
