### ISSUE TITLE
No error in case of unauthorized Publish

### ISSUE THREAD

**Issue by tn185075** [hivemq/hivemq-community-edition#281]
## Expected behavior
When sent a publish request to hivemq broker, with default permissions setup to deny request on a particular topic, The broker should respond with a error code or send a response back in puback.
## Actual behavior
No error/response from the broker.
## To Reproduce
Deny publish on a topic in HiveMQ broker

### Reproducer code
``` go
pb := &paho.Publish{
Topic:   "Hello",
Retain:  true,
Payload: []byte("Hello"),
Properties: &paho.PublishProperties{
	ContentType:   "text/plain",
	// ResponseTopic: responseTopic,
	// User:          pp,
},
}
pr, err := c.Publish(context.Background(), pb)
```
No error sent in response.
## Details
- Affected HiveMQ CE version(s): 2021.1

**Comment by DC2-DanielKrueger** [comment]
What QoS is used per default in this client? And what MQTT Version?

**Comment by tn185075** [comment]
Default QoS is set to 0, but on providing QoS level 1 and 2, the client keeps on reconnecting with the broker.

MQTT version used is 5, But I have tested it with 3.1.1 client as well.

**Comment by tn185075** [comment]
I now seen on adding restrictions in Topic Permission related to QoS,
* QoS 0: Does Nothing
* Qos 1: Error returned along with Reason string.
* QoS 2: No error but reason string contains the Not Authorized error.

Thank you!
Will reopen the issue, in case I face some issues again.

**Comment by DC2-DanielKrueger** [comment]
Just for clarification: QoS-0 can not do anything (except a forceful disconnect of the client - we do not want to do so) as there is no answer such as a puback. Therefor the broker can not tell the client, that something went wrong.
