### ISSUE TITLE
HiveMQ mixing up payloads from different topics

### ISSUE THREAD

**Issue by canique** [hivemq/hivemq-community-edition#306]
## Expected behavior
Setup: Mosquitto 2.0.12 is running as a broker. HiveMQ is configured as a bridge. Mosquitto is publishing topics to HiveMQ.
It's expected that if a msg A has been published to topic X, and to topic X only, A will not show up in topic Y, Z etc.

## Actual behavior
After restarting HiveMQ topic payloads get mixed up on the HiveMQ broker. A Websocket Client connected to HiveMQ starts to see payloads on the wrong topics where they don't belong to.
So if I have e.g. posted a string to a topic c1000/sensors/air/123/label, this string might show up in c1000/sensors/air/123/reading that is supposed to contain only JSON formatted messages. It seems unpredictable where a message will show up.
The exact point in time when this happens is, after the bridge connection mosquitto<->hivemq has been established. Before this connection is established, all the topics are ok.

Important note 1): The bug does not seem to occur if during the re-establishment of the bridge connection between Mosquitto and HiveMQ, no client is connected to HiveMQ. So this could be an important hint: **a client must be connected to HiveMQ for the bug to show up**. This is also the reason why I suspect the bug to be on the HiveMQ side, and not on the Mosquitto side. Because if mosquitto was publishing the wrong messages to the wrong topics, then it would happen on every restart, irrespective of whether a client is connected to HiveMQ or not.

Important note 2): Sometimes topics get fixed to their correct values after a couple of hours. But only on the HiveMQ side, not on the Mosquitto side. (Some errors come through to Mosquitto, because some topics are configured HiveMQ -> Mosquitto)

Bug maybe in JS Lib (Client)? No. Explanation:
I have thought about the possibility that the bug is in the javascript websocket library, and invalid data gets published to HiveMQ. But the permissions are restricted so that HiveMQ allows publishes only on "label" topics - erroneous publishes are found in topics (sensor readings etc.) where HiveMQ does not have a permission to publish to, that is the JS lib cannot be the source of the trouble. And if the error was on the javascript (client) side, then the same error should occur when connected to the mosquitto broker. It does not happen though.

### Steps
1) Setup Mosquitto with an MQTTv5 bridge over TLSv1.3 and some topics in OUT mode, with HiveMQ as the remote broker
2) MQTT Websocket client connects to HiveMQ
3) Restart HiveMQ
4) MQTT Websocket client tries to reconnect in 2s intervals, eventually reconnects (it reconnects before Mosquitto does)
5) Mosquitto <-> HiveMQ bridge is re-established by Mosquitto
6) topics get overwritten with data from other topics on the HiveMQ side.

## Details
- Affected HiveMQ CE version(s): hivemq-ce-2021.2
- Used JVM version: openjdk 11.0.12

**Comment by MicWalter** [comment]
Hi @canique,

can you try out the current master and check if the issue still arises? Reading your description it sounds very similar to the linked issue one comment above.

Either build zip yourself: https://github.com/hivemq/hivemq-community-edition#building-from-source

Or use nightly build: https://hivemq.github.io/nightly-builds/

Greetings,
Michael from the HiveMQ team

**Comment by canique** [comment]
Hello @MicWalter,

I've downloaded nightly build hivemq-community-edition-master-242c77ab38-1.zip and indeed: the bug is gone.

Before that I could reproduce the bug with a 100% success rate, the topics all look as they should.

Thanks!
