### ISSUE TITLE
failed to create resource: Internal error occurred: failed calling webhook "hivemq-cluster-policy.hivemq.com"

### ISSUE THREAD

**Issue by mokhos** [hivemq/hivemq-community-edition#329]
## Expected behavior
Helmchart to be installed correctly!
## Actual behavior
Giving this error without any special configuration or change in helmchart:
`
failed to create resource: Internal error occurred: failed calling webhook "hivemq-cluster-policy.hivemq.com": Post "https://hivemq-operator-0-1649064099-operator.hivemq.svc:443/api/v1/validate/hivemq-clusters?timeout=30s": service "hivemq-operator-0-1649064099-operator" not found
`
How it is looking for its service with a different name, while the service is created with another name?
### Steps
https://www.hivemq.com/docs/operator/4.7/kubernetes-operator/deploying.html#helm-chart
## Details
- Affected HiveMQ CE version(s): 
- Used JVM version:

**Comment by MicWalter** [comment]
Hi @mokhos,

did you try to deploy the HiveMQ community edition with the operator?

If not please close this issue and reopen it at the appropriate place, in this case: https://github.com/hivemq/hivemq-operator

Greetings,
Michael

**Comment by mokhos** [comment]
> Hi @mokhos,
> 
> did you try to deploy the HiveMQ community edition with the operator?
> 
> If not please close this issue and reopen it at the appropriate place, in this case: https://github.com/hivemq/hivemq-operator
> 
> Greetings, Michael

There is no such repository!

**Comment by MicWalter** [comment]
Oh yes you are right the other one is private 🙃 

I think the helm-charts repo is the next best place
