### ISSUE TITLE
Stuck at installation and the documentation is not helpful

### ISSUE THREAD

**Issue by sanjmeh** [hivemq/hivemq-community-edition#330]
## HiveMQ broker installation process is broken and not detailed enough for troubleshooting
The process documented at the home page of this repo fails many times. There is no way I can raise an issue here or on the community as on the community people just attach a link to this github repo, and I cannot raise any issue on the github repo as it is not a bug.  What if someone does not see the files you are assuming should be there. I have raised my question in detail on the community but of no help. It is already 15 days and I am still unable to install hivemq CE.

https://community.hivemq.com/t/hivemq-community-edition-installation-in-ubuntu-using-aws-ec2-instance/409/8?u=sanjmeh

## Preferred solution or suggestions
Please allow trouble shooting steps in installation. What if a step fails? What if the step gives a warning.

**Comment by gitseti** [comment]
Hi @sanjmeh,

Yes, we could add a small troubleshooting or note section to specific steps. But first let me make sure, that we understood the issues correctly.

For the first linked error, I assume that things resolved after `systemctl daemon-reload` was done? Or how did you solve the issue?

For the `./gradlew clean hivemqZip` step: Did you retry this step? It seems that the gradle daemon was killed by the OS or crashed for some reason? 
You could try out one of the following

```bash
./gradlew clean hivemqZip "-Dorg.gradle.jvmargs=-Xmx2g -XX:MaxPermSize=2048m"
```

OR

```bash
./gradlew clean hivemqZip --no-daemon 
```

Please let us know what would have helped you in troubleshooting the occured issues or what problems you encountered.

**Comment by sanjmeh** [comment]
I got a response on the hivemq CE community page telling me that the steps on github is to build from source while I can just do a binary download and unzip. The thing that was confusing is there are two installation documents and two links are circulating.. and they are being interchangeably referred for answering my question:
1. https://www.hivemq.com/docs/hivemq/4.7/user-guide/install-hivemq.html
2. This github repo home page.

It could be helpful to cross reference them and not duplicate the steps. Also to make it clear when do we use which one.

Note: I have been asked to ditch the fradle method and go by binary. If I go back to gradle i will try your above steps.

**Comment by DC2-DanielKrueger** [comment]
This issue seems to be resolved. I will close the issue for now.
