### ISSUE TITLE
Installation Document slightly wrong and inconsitent

### ISSUE THREAD

**Issue by djsjo** [hivemq/hivemq-community-edition#342]
## Expected behavior
the document should either change the download link in 1. to "git clone..." and the current source code e.g.  [this](https://github.com/hivemq/hivemq-community-edition/wiki/Installing-HiveMQ).

Then it would be correct that the zip file is generated in build/zip.

Or change it that it explains that the zip file is in "build/distributions"
## Actual behavior
the recommended link https://github.com/hivemq/hivemq-community-edition.git leads to the master branch i suppose and not to the current release. Here the gradle files differ a little bit and the zip file is generated in build/distributions instead of build/zip.

### Steps
To reproduce just follow the installation as explained in the beginning very carefully

## Details
- Affected HiveMQ CE version(s): latest
- Used JVM version: jdk 11

**Comment by DC2-DanielKrueger** [comment]
Thanks very much for your feedback, I updated the documentation.
Best Regards, 
Daniel
