### ISSUE TITLE
Auto scaling on k8s env

### ISSUE THREAD

**Issue by janiu-001** [hivemq/hivemq-community-edition#349]
Hi Expert, 

Just wanna confirm how could we support auto scaling in k8s cluster? Very appreciated for your response

Br
Baoke

**Comment by jumoog** [comment]
the CE Version has no cluster support. For cluster support you need the Professional Version.

**Comment by janiu-001** [comment]
Thanks very much for your quick response.

1. Is the Professional version billed?
2. Does it support scaling? Would you like to simple introduce the mechanism ? does it depend on the k8s HPA?

**Comment by pglombardo** [comment]
Hi @janiu-001 - apologies for the delay.  A comparison of all of the HiveMQ editions is available here:
https://www.hivemq.com/webinars/how-to-setup-run-and-scale-a-secure-mqtt-broker-on-kubernetes/

And there is a whitepaper available if you are interested:
https://www.hivemq.com/solutions/technology/kubernetes/

I'll close this issue, but if anything remains, feel free to re-open or file another issue.
