### ISSUE TITLE
[Docker] Use JIB for docker image build

### ISSUE THREAD

**Issue by lcacciagioni** [hivemq/hivemq-community-edition#350]
## Problem or use case

Using normal docker builds as the project does today could lead to big inefficiencies in regards to the layering and security of this OCI docker images which ends up being a burden.

## Preferred solution or suggestions

As a proposal it will be nice if the project can use a better tailored tool like Jib from Google Container Tools to build the HiveMQ JDK based solutions. Quoting their Readme:

> Jib builds optimized Docker and [OCI](https://github.com/opencontainers/image-spec) images for your Java applications without a Docker daemon - and without deep mastery of Docker best-practices. It is available as plugins for [Maven](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin) and [Gradle](https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin) and as a Java library.

**Comment by DC2-DanielKrueger** [comment]
We are working on Docker Image Improvements internally (not JIB).

**Comment by SgtSilvio** [comment]
We now provide a multi-arch container image for the platforms linux/amd64 and linux/arm64/v8 since version 2024.3: https://github.com/hivemq/hivemq-community-edition/releases/tag/2024.3
