### ISSUE TITLE
[JDK] Upgrade to latest LTS version

### ISSUE THREAD

**Issue by lcacciagioni** [hivemq/hivemq-community-edition#354]
## Problem or use case

Given all the improvements in the latest LTS version in regards to several topics it might be advisable to keep up with the latest LTS version (17 at the moment). This will also make easier the transition to the next LTS version (21 which will be GA as of September 2023) and quite probably improve several things like Performance (ZGC and Numa support are way better in version 17) and Features ([More Info](https://dzone.com/articles/whats-new-between-java-11-and-java-17))

## Preferred solution or suggestions

It will be ideal to upgrade to version 17 and use as base one JDK implementation for building from the [most popular as of today](https://newrelic.com/resources/report/2022-state-of-java-ecosystem):

- [Amazon Corretto](https://aws.amazon.com/corretto)
- [Temurin by Adoptium (Formerly AdoptOpenJDK)](https://adoptium.net/temurin/releases)
- Or the normal OpenJDK

**Comment by DC2-DanielKrueger** [comment]
Hey @lcacciagioni , 

Our current policy is to support SDK version 11. Of course you can compile it with a more recent version and/or make changes with the new semantic sugar they offer in an own fork. 

Best Regards, 
Daniel
