### ISSUE TITLE
[JAR] Use proper git storage for binaries

### ISSUE THREAD

**Issue by lcacciagioni** [hivemq/hivemq-community-edition#355]
## Problem or use case

As part of the source code there seems to be several binary files, like `*.jar` files, for which git has pretty poor capabilities of tracking.

## Preferred solution or suggestions

As part of the solution it would be advisable to probably track this binary files with something like [git lfs](https://git-lfs.github.com/) which might be better for tracking this kind of files since its creation was with this intention.

**Comment by jumoog** [comment]
Good idea but Github Git LFS cost money. 50 GB bandwidth cost $5

**Comment by lcacciagioni** [comment]
Wow, didn't knew that one... Long time user of GitLab here... Then probably another alternative can be a gradle process that downloads the jar at assemble time as if it where a dependency, and then the release of this jars can be hosted even as a GitHub Package for JDK or an S3 bucket or whatever public hosting solution you use this days.

**Comment by DC2-DanielKrueger** [comment]
This is not an issue. In the long-run we will get rid of these jar tools anyways.
