### ISSUE TITLE
[SourceCode] Adapt for proper JDK >= 9 support

### ISSUE THREAD

**Issue by lcacciagioni** [hivemq/hivemq-community-edition#356]
## Problem or use case

It seems to be that script `run.sh` enables several backward compatible features that are not enabled by default through the use of `--add-exports` and `--add-opens` which can open the door for unknown behaviours and security issues.

## Preferred solution or suggestions

As an ideal solution the module system should use the default behavior and none of this flags should be present in the default `run.sh` script.

> PS: I haven't read the entire codebase, it will be nice to know where and why they are needed to even evaluate if removal of this is even possible.

**Comment by DC2-DanielKrueger** [comment]
> it will be nice to know where and why they are needed to even evaluate if removal of this is even possible.

Yes, I agree. If you like feel free to dig into this.

**Comment by lcacciagioni** [comment]
Will take a look in December
