### ISSUE TITLE
[Research] GraalVM Native Image build

### ISSUE THREAD

**Issue by lcacciagioni** [hivemq/hivemq-community-edition#357]
## Problem or use case

It will be nice to research and see if it is possible to create a native image build that might improve the performance and memory consuption under the right conditions.

## Preferred solution or suggestions

Maybe using the official [GraalVM Gradle Plugin](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html).

**Comment by DC2-DanielKrueger** [comment]
This will not work properly with the current DI framework. Also the use case and benefits are not really clear.
