### ISSUE TITLE
HiveMQ CC - Session Expired over and over again..

### ISSUE THREAD

**Issue by mikementzmaersk** [hivemq/hivemq-community-edition#364]
Fresh installation using hivemq kubernetes operator, and we get this over and over again, there is no way to get past it.
Doesn't seem to matter if it is exposed on ingress-nginx or as a direct k8s loadbalancer - same no matter.

Any pointers on things to check please?

![image](https://user-images.githubusercontent.com/70692508/195852523-5df068b1-c85c-49c7-9725-5f031b1d94f6.png)

**Comment by mikementzmaersk** [comment]
Just in case anyone else comes across this, the bug is all about sticky sessions and load balancing. 

Seems the dashboard doesn’t like it if session is load balanced across brokers. 

Annotating ingress object for a sticky session seems to resolve, likewise if using k8s service type loadbalancer, then session affinity also helps.

**Comment by fraschbi** [comment]
Solved by issuers. Not a community edition issue. This Github repo issue tracker exists to track issues with the HiveMQ Community Edition.
For future reference feel free to use the [HiveMQ Community Forum](https://community.hivemq.com/) to discuss our commercial offerings.
