### ISSUE TITLE
How to change the partition configuration of kafka topic when mqtt is transferred to kafka?

### ISSUE THREAD

**Issue by springmvcGitHub** [hivemq/hivemq-community-edition#365]
hi guys,As described in the document, the default number of partitions is 10. How to change the value of this partition?
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/42227896/196582338-c6a3a831-bb3c-4a1e-9734-1643a96dccc3.png">

**Comment by DC2-DanielKrueger** [comment]
Hey @springmvcGitHub, 

this question fits better in the HiveMQ Community Forum (https://community.hivemq.com/), because the Kafka Extension is not part of the HiveMQ Community Edition. I will close this issue now, feel free to open a thread in the forum.

Best Regards, 
Daniel
