### ISSUE TITLE
A large number of publishers are offline leading to CPU high load

### ISSUE THREAD

**Issue by kenuestar** [hivemq/hivemq-community-edition#395]
## Problem or use case
Hi
During my development, I found that **com.hivemq.persistence.local.IncomingMessageFlowInMemoryLocalPersistence** has some problems.

The first question is that publish will be stored in BackingMap. If Payload is very large, it will increase the memory usage rate of BackingMap. And the publish is just used in com.hivemq.mqtt.handler.publish.PublishFlowHandler.handlePublish.

The second question is when the publisher is offline, it needs to traverse the BackingMap to clear the MESSAGEWID. When the number of publishers is large, it will cause multiple threads to block the backingMap.

## Preferred solution or suggestions
The first problem solution is to store Publish without Payload.

The second problem is to modify the storage data structure.Maintain a map for each client to solve the thread competition problem.
Use 
**ConcurrentHashMap<clientId, ConcurrentHashMap<messageId, MessageWithID>>(ConcurrentHashMap<String, ConcurrentHashMap<Integer, MessageWithID>>)** 
to replace 
**ConcurrentHashMap<MessageFlowKey, MessageWithID>**.

**Comment by pglombardo** [comment]
Hi @kenuestar - thanks for posting.  We'll have someone get back in touch soon!

**Comment by pglombardo** [comment]
Hi @kenuestar - thanks for the analysis and proposal.  To verify, could you provide steps on how we could reproduce this issue ourselves?

How do you trigger the high CPU load and what is the definition of that exactly (20% sustained? 80% load continuous)?

Something so we can easily reproduce the before case to compare any improvements to.

Thanks!

**Comment by kenuestar** [comment]
Hi @pglombardo - thank you very much for your answer.

When each client in the Map has only a small number of PUBLISH messages, there is no such problem of excessive load. However, when multiple clients have a large number of PUBLISH messages in the Map, if these clients are offline, the system load will be too high.
