### ISSUE TITLE
Produce a multiplatform Docker image that supports linux/amd64, linux/arm64 & darwin/arm64

### ISSUE THREAD

**Issue by matthewadams** [hivemq/hivemq-community-edition#397]
## Problem or use case
The Docker image currently published by this project only supports platform `linux/amd64`.

## Preferred solution or suggestions
Use `buildx` to produce a multiplatform Docker image that supports `linux/amd64`, `linux/arm64` & `darwin/arm64`.

**Comment by matthewadams** [comment]
FYI, the `docker:cli` Docker image makes this pretty easy, as it already has `buildx` installed in it.

**Comment by pglombardo** [comment]
Hi @matthewadams - thanks for the request and we concur.  There have been some activity in this area internally but nothing has been released yet.  

Once we add support for the additional architectures, we'll update this issue to let you know.

**Comment by SgtSilvio** [comment]
We now provide a multi-arch container image for the platforms `linux/amd64` and `linux/arm64/v8` since version 2024.3: https://github.com/hivemq/hivemq-community-edition/releases/tag/2024.3
