### ISSUE TITLE
Publish arm64 container on Docker Hub

### ISSUE THREAD

**Issue by rhwood** [hivemq/hivemq-community-edition#427]
## Problem or use case

I would like to be able to run the hivemq-ce container on either of my MacBooks while developing against it without having to build the container myself. Currently I can download the amd64 container from Docker Hub on my older Intel MacBook, but not my newer Apple Silicon MacBook.

## Preferred solution or suggestions

Please publish arm64 containers of hivemq-ce on Docker Hub.

**Comment by rhwood** [comment]
I've since learned that Podman on Apple Silicon devices can run either arm64 or amd64 containers if the architecture is specified with `--arch arm64` or `--arch amd64`, so if you choose to reject this, please update your documentation to include the `--arch amd64` argument.

**Comment by pglombardo** [comment]
Hi @rhwood - thanks for the Podman tip.  That's useful.

I do know that the team is working internally to add arm64 support.  There is no ETA as of yet but we'll update here once we have some progress to report.

**Comment by SgtSilvio** [comment]
We now provide a multi-arch container image for the platforms `linux/amd64` and `linux/arm64/v8` since version 2024.3: https://github.com/hivemq/hivemq-community-edition/releases/tag/2024.3
