### ISSUE TITLE
JWT Authentication extension started but clients can not connect to broker

### ISSUE THREAD

**Issue by dalbarracin** [hivemq/hivemq-community-edition#433]
Hi :)

The current community version of hivemq allows to integrate the Enterprise security extension as a trial mode. In this scenario, the configuration made according to the documentation is the one that covers JWT Authentication with Client Credential Grant type.

There is no clear and detail example about how to configure this locally (only cloud solutions) for testing purpose in regards of the Grant type, but I tried my best effort on guessing what is needed (Jwks and introspection endpoints) for integration with Ory Hydra.

The `conf.xml` file was copied in the `hivemq -enterprise-security-extension` root location as the docs mention as well as disabled all other extensions, but while running the application, it prompts the next:

```
...
Started HiveMQ Enterprise Security Extension successfully.
Extension "HiveMQ Enterprise Security Extension" version 4.22.0 started successfully.

No security extension present, MQTT clients can not connect to this broker.
```

Of course, if some clients try to Authenticate into HiveMQ by a Client library (C# in my case) those will be not authorized, which I thing is the correct behavior.

Please consider this report more as a question/discussion rather than an issue, because probably I am missing something else.

Is there any possibility to get an example how it must be effectively configured for such as grant type and any federation server?

I would like pretty much to get more guidance on this, since I have researched intensively in the documentation as well as the community portal and no clear answers in regards, only motivations to integrate cloud solutions.

Best regards.

**Comment by MicWalter** [comment]
Hi @dalbarracin,

the HiveMQ Community Edition can't run enterprise extensions. That is what I get when I try to start ESE with the community edition:
```
2023-12-06 18:55:19,209 WARN  - Extension /Users/mwalt/Downloads/hivemq-ce-2023.10/extensions/hivemq-enterprise-security-extension cannot be loaded. The class com.hivemq.extensions.security.EnterpriseSecurityMain cannot be instantiated, reason: com/hivemq/extension/sdk/api/services/controlcenter/ControlCenterService
```

I think the best way for you to get help, is by asking in the community forum: https://community.hivemq.com/

Closing this ticket as it's unrelated to HiveMQ CE.

Greetings!
