### ISSUE TITLE
Notification if HiveMQ starts without Security Extension in CE

### ISSUE THREAD

**Issue by dobermai** [hivemq/hivemq-community-edition#56]
**Acceptance Criteria:**

- Notification occurs if HiveMQ has been started without security extension

- Notification doesn't occur if HiveMQ has been starten with security extension

- The notification is big and can't be overseen

- The notification occurs at HiveMQ start up

- If this notification occurs HiveMQ can be stopped immediately

**Comment by SgtSilvio** [comment]
> * If this notification occurs HiveMQ can be stopped immediately

No clients can connect if no security extension is present. So HiveMQ can be stopped without creating a time window where unauthenticated clients can connect.
