### ISSUE TITLE
missing cluster feature, what time will open source?

### ISSUE THREAD

**Issue by pipinet** [hivemq/hivemq-community-edition#6]

**Comment by fraschbi** [comment]
Hello pipinet,
Nice to see your interest in the HiveMQ Community Edition.

The purpose of our GitHub Issue tracker is to keep track of potential issues within the HiveMQ Community Edition. 
Please consider our READ.ME 

> The ideal place for questions or discussions about the HiveMQ Community Edition is our brand new [HiveMQ Community Forum](community.hivemq.com).

and refer your questions to the HiveMQ Community Forum in the future.

In regards to you question at hand:
As stated in our [news release](https://www.hivemq.com/news/hivemq-launches-new-open-source-mqtt-community/)

> HiveMQ Community Edition (CE) is an open source Java-based MQTT broker that implements the complete MQTT 3.x and MQTT 5 broker specification. A well defined set of APIs will allow developers to easily extend the HiveMQ CE platform to integrate MQTT and HiveMQ with other open source projects and enterprise systems. 

More details about the different HiveMQ editions can be found [here](https://www.hivemq.com/hivemq/editions).

Thank you and kind regards,
Florian
