### ISSUE TITLE
Extension System: getPassword in connect packet

### ISSUE THREAD

**Issue by dobermai** [hivemq/hivemq-community-edition#60]
Offer getPassword additionally as byte array in connect packet in the extension system

convenience method

**Comment by pglombardo** [comment]
This now exists in [the Extension SDK](https://github.com/hivemq/hivemq-extension-sdk/blob/29e43068966022875ced41fff2a2c62bc46a00fc/src/main/java/com/hivemq/extension/sdk/api/packets/connect/ConnectPacket.java#L201-L210).
