### ISSUE TITLE
Bridge between HiveMQ CE as local broker and HiveMQ commercial editions in cloud. 

### ISSUE THREAD

**Issue by obersthofer** [hivemq/hivemq-community-edition#71]
HiveMQ CE is sometimes a good fit for local installations with small amount of messages and connections. Therefore it would be great in some use cases to use the HiveMQ CE as local MQTT broker and bridge it to a commercial Version of HiveMQ in the cloud.

**Comment by MicWalter** [comment]
Possible solution: https://www.hivemq.com/extension/enterprise-bridge-extension/

This is a commercial extension that allows to bridge from a HiveMQ enterprise version to other brokers which support MQTT 5.

**Comment by DC2-DanielKrueger** [comment]
Can this be closed?

**Comment by MicWalter** [comment]
Closing this issue as a solution was provided
