### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by caevv** [hivemq/hivemq-community-edition#8]
Are you going to support an official docker image?

**Comment by fraschbi** [comment]
Hello Carlos,
Nice to see your interest in the HiveMQ Community Edition.

The purpose of our GitHub Issue tracker is to keep track of potential issues within the HiveMQ Community Edition. 
Please consider our READ.ME 

> The ideal place for questions or discussions about the HiveMQ Community Edition is our brand new [HiveMQ Community Forum](community.hivemq.com).

and refer your questions to the HiveMQ Community Forum in the future.

In regards to an official Docker image:
It is very likely that we will be releasing an officially supported Docker image in the future. We are also willing to look at outside contributions about the matter, in case you follow our [contribution guidelines](https://github.com/hivemq/hivemq-community-edition/blob/master/CONTRIBUTING.adoc).

Thank you and kind regards,
Florian
