### ISSUE TITLE
Cannot find running process and physical processor on arm64

### ISSUE THREAD

**Issue by mzy2240** [hivemq/hivemq-community-edition#93]
## Expected behavior
No error?

## Actual behavior
Error in the output:
Sep 12 00:11:13 Khadas run.sh[5616]: 2019-09-12 00:11:12,921 INFO  - Log Configuration was overridden by /home/khadas/Downloads/hivemq-ce-2019.1/conf/logback.xml
Sep 12 00:11:13 Khadas run.sh[5616]: 2019-09-12 00:11:13,647 INFO  - This HiveMQ ID is QzF87
Sep 12 00:11:18 Khadas run.sh[5616]: 2019-09-12 00:11:18,421 INFO  - Starting HiveMQ extension system.
Sep 12 00:11:18 Khadas run.sh[5616]: 2019-09-12 00:11:18,459 INFO  - Starting TCP listener on address 0.0.0.0 and port 1883
Sep 12 00:11:18 Khadas run.sh[5616]: 2019-09-12 00:11:18,554 INFO  - Started TCP Listener on address 0.0.0.0 and on port 1883
Sep 12 00:11:18 Khadas run.sh[5616]: 2019-09-12 00:11:18,555 INFO  - Started HiveMQ in 5772ms
Sep 12 00:11:18 Khadas run.sh[5616]: 2019-09-12 00:11:18,641 ERROR - Couldn't find any running processes, which is odd since we are in a running process. Process time values are in jiffies, not milliseconds.
Sep 12 00:11:18 Khadas run.sh[5616]: 2019-09-12 00:11:18,815 ERROR - Couldn't find any running processes, which is odd since we are in a running process. Process time values are in jiffies, not milliseconds.
Sep 12 00:11:18 Khadas run.sh[5616]: 2019-09-12 00:11:18,828 ERROR - Couldn't find physical processor count. Assuming 1.
Sep 12 00:11:18 Khadas run.sh[5616]: 2019-09-12 00:11:18,829 ERROR - Couldn't find physical package count. Assuming 1.

### Steps
Download the zip file, unzip and run according to the instruction. Then in the terminal there are errors in the output. Perhaps it is due to the arm64?

## Details
- Affected HiveMQ CE version(s): 2019.1
- Used JVM version:

**Comment by SgtSilvio** [comment]
Hi @mzy2240,
Thank you for your report.
Could you please answer the following questions:
Does HiveMQ work nonetheless?
Which operating system are you using?
Which hardware are you using?

**Comment by SgtSilvio** [comment]
The error logs only mean that some CPU related metrics are not available (because you use an unknown hardware).
HiveMQ should work without any problems.
@mzy2240 : If you run into any problems, please open a new issue.
